language: node_js

node_js:
  - "4.0.0"

branches:
  only:
    - master
    - develop

services:
  - mongodb

addons:
  ssh_known_hosts: 128.199.39.245

before_install:
  - openssl aes-256-cbc -K $encrypted_48afa7b4060f_key -iv $encrypted_48afa7b4060f_iv
    -in deploy_key.enc -out deploy_key -d

install:
  - npm install
  - npm install -g pm2
  - bower install

script:
  # test running

after_success:
  - chmod 600 deploy_key
  - mv deploy_key ~/.ssh/id_rsa

deploy:
  - provider: script
    script: pm2 deploy production
    on:
      branch: master

  - provider: script
    script: pm2 deploy dev
    on:
      branch: develop
